name: Veracode Policy Scan - Security Gating

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Scan Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: ./target/*.war

  policy-scan:
    name: Veracode Policy Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact V3
        uses: actions/download-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode-artifact

      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode-artifact | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      # run the policy scan action
      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@main
        id: upload_and_scan
        with:
          appname: vincent-github/integrate-with-veracode
          createprofile: true
          policy: 'Verademo Policy'
          version: '${{ github.run_id }}'
          filepath: ./veracode-artifact/${{ env.veracode_artifact }}
          deleteincompletescan: true
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          #scanpollinginterval: 30
          # scantimeout: 60
          # include: ${{ inputs.moddules_to_scan }}
          failbuild: true
          #teams: "Team 7, Team 5, Team A"
          # createsandbox: ${{ inputs.createsandbox }}
          # sandboxname: ${{ inputs.sandboxname }}
