name: Shift Security Left - Veracode Pipeline Scan

on:
  push:
    branches:
      - feature/**

jobs:
  build:
    name: Build Scan Artifact
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: ./target/*.war

  pipeline-scan:
    name: Veracode Pipeline Scan
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download artifact V4
        uses: actions/download-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode-artifact

      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode-artifact | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      - name: Get Veracode Policy Name
        uses: veracode/workflow-app-helper@main
        id: get_policy_name
        with:
          action: 'getPolicyNameByProfileName'
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          appname: vincent-github/integrate-with-veracode
      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.11
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: ./veracode-artifact/${{ env.veracode_artifact }}
          fail_build: true
          veracode_policy_name: ${{ steps.get_policy_name.outputs.policy_name }}

      - name: Veracode Pipeline Results
        if: always()
        id: prepare-results
        uses: Veracode/github-actions-integration-helper@allow-for-non-workflow-app
        with:
          action: 'preparePipelineResults'
          token: ${{ secrets.GITHUB_TOKEN }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          appname: vincent-github/integrate-with-veracode
          # pipeline_scan_flaw_filter: all_results # All pipeline scan results
          # pipeline_scan_flaw_filter: policy_violations # Pipeline scan results that violate the security policy
          # pipeline_scan_flaw_filter: unmitigated_results # Pipeline scan results excluding mitigated findings in the platform
          # pipeline_scan_flaw_filter: unmitigated_policy_violations # Pipeline scan results that violate the security policy and are unmitigated
          # pipeline_scan_flaw_filter: new_findings # New results in this commit not seen in previous scans
          pipeline_scan_flaw_filter: new_policy_violations # New results in this commit that violate the policy
          workflow_app: false
          line_number_slop: 50 # adjust to allow for line number movement
          
 
